Algoritmo "DesvioCondicional02"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Desvios Condicionais 02
// Autor(a)    : João Dias
// Data atual  : 25/08/2021
Var
// Seção de Declarações das variáveis
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Desvio Condicional Simples")
Escreval("Digite sua idade:")
Leia(idade)
Se (idade>=18) entao
   Escreval("Sua idade é maior que 18")
   Senao
Fimse

Fimalgoritmo