Algoritmo "DIVISIVEISPOR4LACOREPITA"
// Lógica de Programação de Javascript
// Jailson 
// Descrição   : Apresentar todos os números divisíveis por 4 menores que 200
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
se (cont % 4 = 0) entao
escreval("Esse número é divisível por 4:", cont)
fimse
cont<-cont+1
ate cont > 200

Fimalgoritmo