Algoritmo "GRAOS"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Apresentar a somatória do número de grãos
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
   // Seção de Declarações das variáveis
   b,c,s,d: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   b<-2
   c<-1
   d<-1
   s<-1
   repita
      d<-b
      c<-c+1
      s<-s+d
   ate c>63
   escreval("A soma é igual:", s)

Fimalgoritmo