Algoritmo "LACOPARA"
// Lógica de Programação de Javascript
// Jailson 
// Descrição   : Exemplo do laço de repetição para
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 1 ate 10 passo 1 faca
escreval("Laço PARA")
fimpara

Fimalgoritmo