Algoritmo "LAÇOREPETICAOENQUANTO"
// Lógica de Programação de Javascript
// Jailson 
// Descrição   : Irá usar o laço de repetição para exibir várias vezes uma mensagem
// Autor(a)    : João Dias
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto i<10 faca
Escreval("Mensagem sendo repetida")
i<-i+1
fimenquanto

Fimalgoritmo