Algoritmo "NUMEROSIMPARES"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Mostar todos os números ímpares de 0 a 20
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
   // Seção de Declarações das variáveis
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto i <= 20 faca
      se (i % 2 = 1) entao
         escreval("Número impar:", i)
      fimse
      i<-i+1
   fimenquanto

Fimalgoritmo