Algoritmo "QUADRADOSLACOPARA"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Mostrar os quadrados dos números de 15 aa 200
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
   // Seção de Declarações das variáveis
   cont: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 15 ate 200 passo 1 faca
   escreval("O quadrado de", cont, " é", cont*cont)
   fimpara

Fimalgoritmo