Algoritmo "QUADRADOS"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Irá ler os quadrados dos números interos de 15 a 200
// Autor(a)    : João Dias
// Data atual  : 01/09/2021
Var
   // Seção de Declarações das variáveis
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i<-15
   repita
      escreval("O quadrado de", i, " é:", i*i)
      i<-i+1
   ate i = 200

Fimalgoritmo