Algoritmo "QUADRADOSLACOREPITA"
// Lógica de Programação de Javascript
// Jailson 
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-15
repita
Escreval("O quadrado de", cont, " é", cont*cont)
cont<-cont+1
ate cont > 200

Fimalgoritmo