Algoritmo "RELOGIO"
// Lógica de Programação de Javascript
// Jailson
// Descrição   : Um relógio no laço PARA
// Autor(a)    : João Dias
// Data atual  : 03/09/2021
Var
   // Seção de Declarações das variáveis
   cont, cont1: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 0 ate 59 passo 1 faca
      para cont1 de 0 ate 59 passo 1 faca
         escreval(cont," : ", cont1)
      fimpara
   fimpara

Fimalgoritmo