Algoritmo "SOMADOS100"
// Lógica de Programação de Javascript
// Jailson 
// Descrição   : Irá calcular a soma dos 100 primeiros números
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
i, somatorio: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i<-1
enquanto i<101 faca
somatorio<-somatorio+i
i<-i+1
fimenquanto
escreval("A soma dos 100 primeiros números é de:", somatorio)
Fimalgoritmo