Algoritmo "Temperaturas"
// 
//  Disciplina: [Lógica de Programação de Javascript]
// Descrição   : Converte a temperatura de celsius para fahrenheit
// Autor(a)    : João Dias
// Data atual  : 25/08/2021
Var
// Seção de Declarações das variáveis 
tc, rf: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Informe o valor da temperatura em celsius C° a ser convertida:")
Leia(tc)

tf<-(tc*1.8) + 32

Fimalgoritmo